"""add is_saved to trips

Revision ID: 203e12ed74a8
Revises: 3387ee7fa5d6
Create Date: 2026-10-03 20:47:50.734011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203e12ed74a8'
down_revision: Union[str, Sequence[str], None] = '3387ee7fa5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_saved')
    # ### end Alembic commands ###
