"""add recommended hotel to agent runs

Revision ID: 3c5e51b520b7
Revises: f9ddeeaa1f50
Create Date: 2026-10-10 08:37:23.513734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5e51b520b7'
down_revision: Union[str, Sequence[str], None] = 'f9ddeeaa1f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('recommended_hotel', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'recommended_hotel')
    # ### end Alembic commands ###
