"""add resolved destination fields to trips

Revision ID: a29b147f16ef
Revises: 73ae02272b2e
Create Date: 2026-09-18 15:12:06.327308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29b147f16ef'
down_revision: Union[str, Sequence[str], None] = '73ae02272b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('destination_name', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('destination_country', sa.String(length=100), nullable=True))
    op.add_column('trips', sa.Column('destination_country_code', sa.String(length=10), nullable=True))
    op.add_column('trips', sa.Column('destination_latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('trips', sa.Column('destination_longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('trips', sa.Column('destination_timezone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_timezone')
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'destination_country_code')
    op.drop_column('trips', 'destination_country')
    op.drop_column('trips', 'destination_name')
    # ### end Alembic commands ###
