"""create selected hotels table

Revision ID: ad39ce398b53
Revises: aea7c5b239d2
Create Date: 2026-10-08 15:38:46.039390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad39ce398b53'
down_revision: Union[str, Sequence[str], None] = 'aea7c5b239d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_offer_id', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.String(length=255), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('converted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('converted_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('hotel_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_hotels_trip_id'), 'selected_hotels', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selected_hotels_trip_id'), table_name='selected_hotels')
    op.drop_table('selected_hotels')
    # ### end Alembic commands ###
