"""add grounding fields to itinerary items

Revision ID: bbab60c58ba6
Revises: a29b147f16ef
Create Date: 2026-09-19 22:11:11.102339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbab60c58ba6'
down_revision: Union[str, Sequence[str], None] = 'a29b147f16ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "itinerary_items",
        sa.Column(
            "activity_type",
            sa.String(length=30),
            nullable=True,
        ),
    )

    op.add_column(
        "itinerary_items",
        sa.Column(
            "place_id",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE itinerary_items
        SET activity_type = 'generic'
        WHERE activity_type IS NULL
        """
    )

    op.alter_column(
        "itinerary_items",
        "activity_type",
        existing_type=sa.String(length=30),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_items', 'place_id')
    op.drop_column('itinerary_items', 'activity_type')
    # ### end Alembic commands ###
