"""add canonical origin fields

Revision ID: be427fded315
Revises: f7af16a8594f
Create Date: 2026-09-21 08:32:05.093059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be427fded315'
down_revision: Union[str, Sequence[str], None] = 'f7af16a8594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('origin_name', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('origin_country', sa.String(length=100), nullable=True))
    op.add_column('trips', sa.Column('origin_country_code', sa.String(length=10), nullable=True))
    op.add_column('trips', sa.Column('origin_latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('trips', sa.Column('origin_longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('trips', sa.Column('origin_timezone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'origin_timezone')
    op.drop_column('trips', 'origin_longitude')
    op.drop_column('trips', 'origin_latitude')
    op.drop_column('trips', 'origin_country_code')
    op.drop_column('trips', 'origin_country')
    op.drop_column('trips', 'origin_name')
    # ### end Alembic commands ###
