"""create trip preferences table

Revision ID: e38e8057061c
Revises: bbe5fe6808d2
Create Date: 2026-09-16 20:12:25.064265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38e8057061c'
down_revision: Union[str, Sequence[str], None] = 'bbe5fe6808d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('pace', sa.String(length=20), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('ai_brief', sa.Text(), nullable=True),
    sa.Column('budget_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', name='uq_trip_preferences_trip_id')
    )
    op.create_index(op.f('ix_trip_preferences_trip_id'), 'trip_preferences', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_preferences_trip_id'), table_name='trip_preferences')
    op.drop_table('trip_preferences')
    # ### end Alembic commands ###
