"""add duration minutes to itinerary items

Revision ID: f9ddeeaa1f50
Revises: ad39ce398b53
Create Date: 2026-10-10 06:23:00.787779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ddeeaa1f50'
down_revision: Union[str, Sequence[str], None] = 'ad39ce398b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_items', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_items', 'duration_minutes')
    # ### end Alembic commands ###
